trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    imageUri: gcr.io/qc-cloud-spring-2023-cnn/mnist_classification_multiworker@sha256:e9cab099a7fcf0ae5103174b357a6606f8022bfddd6e3519c28bd67da04c4bc9

  useChiefInTfConfig: true
  workerType: n1-standard-4
  workerCount: 1
  workerConfig:
    imageUri: gcr.io/qc-cloud-spring-2023-cnn/mnist_classification_multiworker@sha256:e9cab099a7fcf0ae5103174b357a6606f8022bfddd6e3519c28bd67da04c4bc9
